[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."update-blog"]
  schedule = "@weekly"

[[redirects]]
  from = "/pages/courts/:city-florida"
  to = "/pages/courts/:city-florida.html"
  status = 301
  force = true

[[redirects]]
  from = "/pages/:page"
  to = "/pages/:page.html"
  status = 301
  force = true